- name: Add environment variables to /etc/environment
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
    create: yes
    state: present
  with_items:
    - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    - SONAR_HOME=/opt/sonarqube
    - PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/sonarqube/bin"


- name: Append SonarQube to PATH
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^PATH='
    line: 'PATH="$PATH:/opt/sonarqube/bin"'
    state: present
  become: yes

